sudo: false
cache: bundler

script: "bundle exec rake spec"

rvm:
  - 2.1.5
  - 2.2.2

env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql

before_script:
  - cd spec/dummy; bundle exec rake db:setup; cd ../..
  - cd spec/dummy; bundle rake db:test:prepare; cd ../..

bundler_args: "--binstubs --without development"

# IRC notification
notifications:
  irc: "irc.freenode.org#cyt"
